# Generated by Django 3.2 on 2021-05-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mini_goal',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='mini_goal',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='mini_goal',
            name='day3',
        ),
        migrations.AddField(
            model_name='mini_goal',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.skill'),
        ),
    ]
