# Generated by Django 3.2 on 2021-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini_goal',
            name='consistency',
            field=models.FloatField(null=True),
        ),
    ]
