# Generated by Django 3.2 on 2021-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_mini_goal_mini_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_goal',
            name='mini_goal',
            field=models.TextField(max_length=300),
        ),
    ]
