# Generated by Django 3.2 on 2021-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_mini_goal_mini_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini_goal',
            name='skilltext',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
